# Generated by Django 3.2.8 on 2021-11-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('puntos_alquiler', models.IntegerField(default=0)),
                ('localizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkiStickApp.localizacion')),
                ('pista', models.ManyToManyField(related_name='estaciones', to='SkiStickApp.Pista')),
            ],
        ),
    ]
