# Generated by Django 3.2.8 on 2021-11-07 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('puntos_alquiler', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('color_tipo', models.CharField(max_length=30)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkiStickApp.estacion')),
            ],
        ),
        migrations.AddField(
            model_name='estacion',
            name='localizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkiStickApp.localizacion'),
        ),
    ]
