# Generated by Django 3.2.9 on 2021-12-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkiStickApp', '0002_alter_estacion_pista'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
    ]
