# Generated by Django 3.2.8 on 2021-12-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkiStickApp', '0005_alter_localizacion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localizacion',
            name='image',
        ),
        migrations.AddField(
            model_name='localizacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
