# Generated by Django 3.2.8 on 2021-12-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SkiStickApp', '0006_auto_20211217_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usu', models.CharField(max_length=30)),
                ('valoracion', models.CharField(max_length=30)),
                ('opinion', models.CharField(max_length=200)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkiStickApp.estacion')),
            ],
        ),
    ]
