# Generated by Django 3.2.8 on 2021-12-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkiStickApp', '0008_alter_opinion_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='valoracion',
            field=models.IntegerField(),
        ),
    ]
